version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-app1
      - frontend-app2
      - frontend-app3
      - backend

  frontend-app1:
    build:
      context: ./frontend
    container_name: frontend-app1

  frontend-app2:
    build:
      context: ./frontend
    container_name: frontend-app2

  frontend-app3:
    build:
      context: ./frontend
    container_name: frontend-app3
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - PORT=5000
    expose:
      - "5000"
