version: "3.8"

services:
  frontend:
    image: petercephas52/portfolio-frontend:latest
    ports:
      - "3000:80"
    restart: always

  backend:
    image: petercephas52/portfolio-backend:latest
    ports:
      - "5001:5001"
    restart: always
