version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: petercephas52/portfolio-backend:latest
    container_name: node-backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
