version: "3.8"

services:
  frontend:
    image: petercephas52/portfolio-frontend:latest
    container_name: portfolio-frontend
    restart: always

  backend:
    image: petercephas52/portfolio-backend:latest
    container_name: portfolio-backend
    env_file:
      - ./backend/.env
    restart: always
