name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: http://34.201.251.67:5001

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-frontend:latest
          platforms: linux/amd64
          build-args: |
            REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest
          platforms: linux/amd64

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf my-portfolio
            git clone https://github.com/VenkateshV14/my-portfolio.git
            cd my-portfolio
            echo "REACT_APP_API_URL=http://34.201.251.67:5001" > frontend/.env
            docker compose pull
            docker compose up -d
            docker image prune -af --filter "until=1h"
            docker system prune -af --volumes
